Environment variables
ink8bit/urlshort pull request #5
Opened 2023-11-06 09:28 UTC by ink8bit

2023-11-07 15:23 UTC, arttet requested changes
Please read it
https://cbea.ms/git-commit/
https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

Please add linters in CI https://github.com/golangci/golangci-lint
Please add the code coverage report in CI https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
Please add gofmt in CI https://github.com/marketplace/actions/check-code-formatting-using-gofmt

2023-11-07 15:23 UTC, arttet commented on internal/shorten/shorten.go
> +func GenStr() string {
```suggestion
func GenRandomStr() string {
```

2023-11-07 15:23 UTC, arttet commented on internal/app/handlers.go
> +	findURL = storage.FindURL
Please avoid global variables
If it is for testing purposes, it should be in the test package

2023-11-07 15:23 UTC, arttet commented on internal/storage/storage.go
> +// NOTE: it's a temporary solution.
```suggestion
// TODO: it's a temporary solution.
```
I like this comment. But let's fix this issue and exclude using global variables.

2023-11-07 15:23 UTC, arttet commented on internal/storage/storage.go
> +func SaveURL(origURL string) string {
What if we get an error?

2023-11-11 11:33 UTC, ink8bit commented on internal/storage/storage.go
> +func SaveURL(origURL string) string {
I've change the function signature to `func SaveURL(origURL string) (string, error)`.

2023-11-12 15:51 UTC, arttet approved these changes

2023-11-12 15:51 UTC, arttet commented on .github/workflows/gofmt.yml
> +  golangci:
```suggestion
  gofmt:
```

2023-11-12 15:51 UTC, arttet commented on internal/app/router/router.go
> +	r.Get("/{id:^[0-9A-Za-z]+}", s.OriginURLHandler)
```suggestion
	r.Get("/{id:^[0-9A-Za-z]+$}", s.OriginURLHandler)
```

2023-11-12 15:51 UTC, arttet commented on internal/config/flags.go
> +	Addr    string
Please don't use global variables

2023-11-12 17:03 UTC, merged